#Wired
# Wired Joystick Config
joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: input_joy/cmd_vel
      deadman_buttons: [7]  # Correct button for enabling movement
      axis_mappings:
        linear-x:   # Correct mapping for linear.x
          axis: 3   # Axis for linear motion (usually joystick Y-axis)
          scale: 1.0
          offset: 0.0
        angular-z:  # Correct mapping for angular.z
          axis: 0   # Axis for angular motion (usually joystick X-axis)
          scale: 1.0
          offset: 0.0


#PS4 Wireless
# joy_teleop:
  # ros__parameters:
  #   move:
  #     type: topic
  #     interface_type: geometry_msgs/msg/Twist
  #     topic_name: input_joy/cmd_vel
  #     deadman_buttons: [5]
  #     axis_mappings:
  #       twist-linear-x:
  #         axis: 4
  #         scale: 1.0
  #         offset: 0.0
  #       twist-angular-z:
  #         axis: 0
  #         scale: 1.0
  #         offset: 0.0
