joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min  : 0.05
      linear_forward_max  : 0.35
      linear_backward_min : 0.05
      linear_backward_max : 0.35
      angular_min : 0.35
      angular_max : 2.5
      steps       : 3